version: '3.3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    command:
      [
        'mysqld',
        '--character-set-server=utf8',
        '--collation-server=utf8_turkish_ci',
        '--max_connections=650'
      ]
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: '3096m'
  hangfireService:
    image: hsnakpld/hangfire:latest
    ports:
      - 5001:80
    environment:
      MYSQL_URI: "server=mysql;port=3306;database=root;user=root;password=root;"
      ASPNETCORE_URLS: http://*:80
    depends_on:
      - mysql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: '500m'
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: "replicas"
                value: 3

volumes:
  mysql-volume:
